import { AnticiposReintegros } from "./anticipos-reintegros";
import { ViajesHotel } from "./viajes-hotel";
import { ViajesItinerario } from "./viajes-itinerario";

export class Viajes {
    id_viaje?: number;
    guid?: string;
    codigo?: string;
    id_viajero?: number;
    fecha_inicio_viaje?: string;
    fecha_fin_viaje?: string;
    objetivo?: string;
    anulado?: boolean;
    fecha_crea?: Date;
    numero_cuenta?: string;
    id_tipo_cuenta?: number;
    id_entidad_bancaria?: number;
    fecha_radico_legalizacion?: Date;
    fecha_anulo?: Date;
    motivo_anulo?: string;
    id_usuario_anulo?: number;
    fecha_solicitud?: Date; 
    requiere_anticipo?: boolean;
    itinerario?: ViajesItinerario[]; 
    hotel?: ViajesHotel[]; 
    anticipo?: AnticiposReintegros; 
    // reintegro?: AnticiposReintegros; 
    valor_anticipo?: number; 
    asociado_taller?: boolean; 
    id_taller?: number; 
    id_categoria?: number; 
    nro_horas?: number; 
    nro_dias?: number; 
    categoria?: string; 
    identificacion?: number;
    usuario?: string;
    enviar_aprobacion?: boolean;
    id_usuario?: number;
    id_estado?: number;
    estado?: string;
    taller?: string; // Nombre del taller asociado, si aplica
    tipo_cuenta?: string; // Tipo de cuenta bancaria (opcional)
    entidad_bancaria?: string; // Nombre de la entidad bancaria (opcional)
    id_solicitud_aprobacion?: number;
    es_invitado?: boolean;
    persona_invitada?: string;
    documento_persona_invitada?: string;
    telefono_persona_invitada?: string;
    correo_persona_invitada?: string;
    informe_lugar?: string;
    instituciones_participantes?: string;
    temas_tratados?: string;
    compromisos?: string;
    observaciones_informe?: string;
    tipo_solicitud_aprobacion?: string;
    id_solicitud_aprobacion_legalizacion?: number;
    requiere_tiquetes?: boolean;
    tipo_viaje?: string;
    hora_inicio?: string;
    hora_fin?: string;
    viaje_internacional?: boolean;
    pais?: string;
    fecha_nacimiento_viajero?: Date;
    id_supervisor_aprueba?: number;
    id_rol_aprobacion_supervisor?: number;
    guid_soporte_pasaporte?: string;
    soporte_pasaporte?: string;
    soporte_asistencia_medica?: string;
    guid_usr?: string;
    pendiente_mi_aprobacion?: boolean;
    id_rubro?: number;
    id_proyecto?: number;
    proyecto_rubro?: string;
    orden_actual_solicitud?: number;
    valor_reintegro?: number;
    aprobo_supervisor?: boolean;
    guid_msft_ajuste?: string;
    observaciones_adicionales?: string;
    menciones_json?: string;
    id_usuarios_mencion?: number[];
    pago_anticipo_rechazado?: boolean;
    dias_despues_finalizado?: number;
    legalizacion_fuera_tiempo?: string;
    soporte_informe?: string;
    id_actividad?: number;
    regional?: string;
    relacion_facturas?: boolean;
    id_programa?: number;
    total_registros?: number;
    actividad?: string;
    rubro_corto?: string;
    contacto_emergencia?: string;
    telefono_emergencia?: string;
    parentesco_emergencia?: string;
    constructor(data?: Partial<Viajes>) {
        Object.assign(this, data);
    }
}
